Fix Issue 11. Provide output path
prabhakar267/ocr-convert-image-to-text pull request #16
Opened 2018-03-18 19:55 UTC by rohithredd94

2018-03-19 07:23 UTC, prabhakar267 requested changes

2018-03-19 07:23 UTC, prabhakar267 commented on main.py
> +		directory_path = path + '/converted-text/'
Use `os.path.join()` instead of concatenating the string
`os.path.join()` takes care of trailing slashes

2018-03-19 07:23 UTC, prabhakar267 commented on main.py
> +def main(path, directory_path):
Use more informative variable names like `source_directory` and `target_directory`

2018-03-19 07:23 UTC, prabhakar267 commented on main.py
> +	parser.add_argument('output_dir', nargs='?')
Add help strings if possible.

2018-03-20 03:39 UTC, rohithredd94 commented on main.py
> +	parser.add_argument('output_dir', nargs='?')
What do you mean by add help strings? Argument parser has a flag -h which displays info about positional arguments. This is displayed on using -h flag:
usage: main.py [-h] input_dir [output_dir]

positional arguments:
  input_dir
  output_dir

optional arguments:
  -h, --help  show this help message and exit

What else do you want me to add?

2018-03-20 12:52 UTC, prabhakar267 commented on main.py
> +	parser.add_argument('output_dir', nargs='?')
When a user tries to see help (python main.py -h), we can have him view a custom help message for each argument.
You can have a look at the example from argparse documentation.
Example: https://docs.python.org/2/library/argparse.html#example

2018-03-30 04:01 UTC, rohithredd94 commented
@prabhakar267 I just updated the code with the requested changes. Can you please review them?

2018-04-03 14:09 UTC, prabhakar267 approved these changes

2018-04-03 14:09 UTC, merged