Add command to print ouptut to console
prabhakar267/ocr-convert-image-to-text pull request #39
Opened 2019-07-29 17:53 UTC by allEyezOnCode

For #38

2019-07-30 07:13 UTC, prabhakar267 commented on main.py
> +def main(input_path, output_path, no_output_directory=False):
Why do you need a new parameter to detect is output directory was provided or not?
You can pass `output_path` as `None` and use that as your flag.

2019-07-30 08:25 UTC, allEyezOnCode commented
So the line 141 like that?:
`if os.path.join(input_path, 'converted-text') == output_path:`

2019-07-30 08:41 UTC, allEyezOnCode commented
Or should I rewrite the run_tesseract function to return a list or a dic in case the output_dir flag = none and print the list ?

2019-07-30 09:04 UTC, allEyezOnCode commented
Or should I rewrite the run_tesseract function to return a tempfile in case the output_dir flag = None?

2019-07-30 09:27 UTC, prabhakar267 requested changes

2019-07-30 09:27 UTC, prabhakar267 commented on main.py
> +                for file in os.listdir('{}/converted-text'.format(input_path)):
You have implemented this for each file instead it should be a global flag i.e., if the output_path was not passed in arguments print output of every file on console and do not save it to any file

2019-07-30 09:27 UTC, prabhakar267 commented on main.py
> +def main(input_path, output_path, no_output_directory=False):
Why do you need a new parameter to detect is output directory was provided or not?
You can pass `output_path` as `None` and use that as your flag.

2019-08-01 15:25 UTC, allEyezOnCode commented
So I rewrite the run_tesseract function to return the text in case no output path is provided, I hope it's OK

2019-08-06 15:52 UTC, prabhakar267 approved these changes

2019-08-06 15:53 UTC, merged